const fs = require('fs');
let html = fs.readFileSync('original.html', 'utf8').replaceAll('\r\n','\n');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
let js = scripts.at(-1)[1];
const fixes = fs.readFileSync('fixes.js','utf8').replaceAll('\r\n','\n');
for(const match of fixes.matchAll(/^  (?:async )?function (\w+)\(/gm)) {
  const name = match[1], start = match.index;
  const end = fixes.indexOf('\n  }', start) + 4;
  const re = new RegExp('^  (?:async )?function '+name+'\\(', 'm');
  const old = re.exec(js);
  if (!old) throw Error(name);
  const lineEnd = js.indexOf('\n',old.index);
  const oldEnd = js.slice(old.index,lineEnd).trimEnd().endsWith('}') ? lineEnd : js.indexOf('\n  }',old.index)+4;
  js = js.slice(0,old.index)+fixes.slice(start,end)+js.slice(oldEnd);
}
js = js.replace("if (company)        currentCompany = company;", "if (!currentCompany && COMPANY_PROFILES[company]) currentCompany = company;");
for (const [a,b] of [['users','usuariosBD'],['trains','trenesActivos'],['hist','historial'],['crew','personal'],['locos','locomotoras']]) js = js.replace(new RegExp('if \\('+a+'\\.length\\)\\s+'+b+'\\s*= '+a+';'),b+' = '+a+';');
js = js.replace("} catch (err) { console.error('[FerroSync] Error cargando DB', err); }", "} catch (err) { throw new Error('No se pudieron cargar los datos: ' + err.message); }");
js = js.replace("const syncChannel = new BroadcastChannel('ferrosync_channel');", "const syncChannel = typeof BroadcastChannel === 'function' ? new BroadcastChannel('ferrosync_channel') : { postMessage() {} };");
js = js.replace("const DB_VERSION = 1;", "const DB_VERSION = 1;\n  let revision = 0;");
js = js.replace('await abrirDB();\n      const [company', "await abrirDB();\n      revision = await dbGetConfig('revision') || 0;\n      const [company");
js = js.replace("rolActual = user.role;", "rolActual = user.role;");
js = js.replace("else {\n      document.getElementById('auth-screen').style.display", "else {\n      document.getElementById('company-screen').style.display = 'none';\n      document.getElementById('auth-screen').style.display");
js = js.replace("    rolActual = user.role;", "    document.getElementById('company-screen').style.display = 'none';\n    rolActual = user.role;");
js = js.replace("window.addEventListener('load', iniciarApp);", "window.addEventListener('load', async () => { await iniciarApp(); window.ferroReady = true; });");
js = js.replace("u.name === name && u.pass === pass && u.empresa === currentCompany", "u.name.toLocaleLowerCase('es') === name.toLocaleLowerCase('es') && u.empresa === currentCompany");
js = js.replace('if (!user) {', 'if (!user || !(await verificarClave(user, pass))) {');
js = js.replaceAll("document.getElementById('login-pass').value.trim()", "document.getElementById('login-pass').value");
js = js.replace("    rolActual = '';", "    detenerSeguimiento(); miTren = null; currTramo = null; trenEditando = null;\n    document.getElementById('tramos-lista').replaceChildren(); tramoCount = 0;\n    rolActual = '';");
js = js.replace("    currentCompany = ''; await", "    toggleAuthMode('login'); currentCompany = ''; await");
js = js.replace("    document.querySelectorAll('.nav-item').forEach", "    if (!rolActual || (rolActual === 'Maquinista' && id !== 'operacion') || (rolActual === 'Logística' && id === 'operacion')) return;\n    document.querySelectorAll('.nav-item').forEach");
js = js.replace("historial.filter(t => t.empresa === currentCompany).length", "new Set(historial.filter(t => t.empresa === currentCompany && t.viajeCompletado).map(t => t.nroPlan)).size");
js = js.replace("if(!map) {", "if (!window.L) { document.getElementById('map-container').textContent = 'Mapa no disponible sin conexión. Los viajes siguen disponibles.'; return; }\n    if(!map) {");
js = js.replace("marker.bindPopup(`<b>Tren ${t.nroPlan}</b><br>Tripulación: ${t.conductor}`);", "marker.bindPopup(`<b>Tren ${esc(t.nroPlan)}</b><br>Tripulación: ${esc(t.conductor)}<br>${t.coordsActuales ? 'Última posición GPS: ' + new Date(t.coordsActuales.at).toLocaleString('es-UY') : 'Origen planificado; sin posición GPS'}`);");
// Escape all free text rendered by the original table templates.
js = js.replace(/\$\{(c\.nombre|l\.id|l\.modelo|t\.nroPlan|t\.descripcion|t\.conductor|h\.\w+)\}/g, '${esc($1)}');
js = js.replace("onclick=\"editarTren('${esc(t.nroPlan)}')\"", "data-edit=\"${esc(t.nroPlan)}\"").replace("onclick=\"cancelarTren('${esc(t.nroPlan)}')\"", "data-cancel=\"${esc(t.nroPlan)}\"").replace("onclick=\"toggleEstadoLocomotora('${esc(l.id)}')\"", "data-loco=\"${esc(l.id)}\"");
js = js.replace("${t.ayudante !== 'Ninguno' ? t.ayudante : '—'}", "${esc(t.ayudante !== 'Ninguno' ? t.ayudante : '—')}<br>P: ${esc(t.piloto !== 'Ninguno' ? t.piloto : '—')}");
js = js.replace('<span style="font-size:10px">${esc(t.descripcion)}</span>', '<span style="font-size:10px">${esc(t.descripcion)}</span><br><span style="font-size:11px">${t.salida ? new Date(t.salida).toLocaleString("es-UY") : "Sin horario registrado"}<br>Hasta: ${t.llegada ? new Date(t.llegada).toLocaleString("es-UY") : "—"}</span>');
js = js.replace("if (t.ayudante) ocupados.push(t.ayudante); });", "if (t.ayudante) ocupados.push(t.ayudante); if (t.piloto) ocupados.push(t.piloto); });");
js = js.replace('En Viaje</span>', 'Asignado</span>').replace('Habilitado</span>', 'Sin asignación</span>');
js = js.replace("t.estado === 'Observado'", "pending(t)");
js = js.replace("      const currTramo = t.tramos[t.tramoActualIdx];", "      if (pending(t)) badge += '<span class=\"badge badge-danger\">Imprevistos pendientes</span>';\n      const currTramo = t.tramos[t.tramoActualIdx];");
js = js.replace('${btnAcciones}</td>', '${btnAcciones}<button class="btn btn-outline btn-sm" data-detalle="${esc(t.nroPlan)}">Detalle / PDF</button></td>');
js = js.replace('<td>${esc(h.nroPlan)}</td>', '<td>${esc(h.nroPlan)}<button class="btn btn-outline btn-sm" data-detalle="${esc(h.nroPlan)}">Detalle / PDF</button></td>');
js = js.replace('trenesActivos = trains;', 'trenesActivos = trains; normalizarObservados();');
js += '\n' + fs.readFileSync('helpers.js','utf8').replaceAll('\r\n','\n');
js += '\n' + fs.readFileSync('viajes.js','utf8').replaceAll('\r\n','\n');
js += '\n' + fs.readFileSync('colaboracion.js','utf8').replaceAll('\r\n','\n');
js += '\n' + fs.readFileSync('administracion.js','utf8').replaceAll('\r\n','\n');
html = html.replace(scripts.at(-1)[0], '<script src="app.js"></script>');
html = html.replace(', maximum-scale=1.0, user-scalable=no','');
html = html.replace(/  <script src="https:\/\/(cdnjs|cdn.jsdelivr)[^\n]+\n/g,'');
html = html.replace('FerroSync - Enterprise V4', 'FerroSync — Gestión local');
html = html.replace('<span>GPS Transmitiendo</span>', '<span id="gps-status" role="status">GPS sin activar</span>');
html = html.replace('Tonelaje Total (t)', 'Carga remolcada (t)').replaceAll('LITROS/KMT','LITROS/KM');
html = html.replace('</head>','<link rel="stylesheet" href="correcciones.css"></head>');
html = html.replace(/<body[^>]*>/, '$&<div class="local-notice">Entorno local de pruebas · Datos ferroviarios de ejemplo</div>');
html = html.replace('id="company-screen"', 'id="company-screen" style="display:none"');
html = html.replace('onclick="cerrarSesion()"','aria-label="Cerrar sesión" onclick="cerrarSesion()"').replace('onclick="toggleSidebar()"><i','aria-label="Abrir menú" onclick="toggleSidebar()"><i');
html = html.replace('Guardar Planificación</button>', 'Guardar Planificación</button><button class="btn btn-outline" style="margin-top:12px" onclick="limpiarPlanificacion()">Nueva planificación / cancelar edición</button>');
html = html.replace('<div id="maq-tramo-inicio">', '<div id="maq-novedades"></div><div class="input-group"><label for="maq-novedad">Nueva observación del viaje</label><textarea id="maq-novedad" maxlength="2000"></textarea></div><button class="btn btn-outline" onclick="guardarNovedadOperacion()">Registrar observación</button><button class="btn btn-outline" onclick="abrirDetalle(miTren.nroPlan)">Detalle / PDF</button><div id="maq-tramo-inicio"><div class="input-group"><label for="maq-obs-inicio">Observaciones al iniciar el tramo</label><textarea id="maq-obs-inicio" maxlength="2000"></textarea></div>');
html = html.replace('id="maq-obs"', 'id="maq-obs" maxlength="2000"');
html = html.replace('id="kpi-obs">0</p>', 'id="kpi-obs">0</p><button class="btn btn-outline btn-sm" onclick="abrirObservados()">Ver observados</button>');
html = html.replace('</body>', '<dialog id="detalle-viaje"><button class="btn btn-outline" onclick="document.getElementById(\'detalle-viaje\').close()">Cerrar</button><div id="detalle-contenido"></div></dialog><section id="informe-impresion"></section></body>');
fs.writeFileSync('index.html',html.replace(/[\t ]+$/gm,'')); fs.writeFileSync('app.js',js.replace(/[\t ]+$/gm,''));
fs.mkdirSync('dist',{recursive:true});
for (const file of ['index.html','app.js','correcciones.css','sw.js','manifest.json','icon.svg']) fs.copyFileSync(file,'dist/'+file);
